#!/bin/bash -e
###########################################################################
#
# Hyperbox - Virtual Infrastructure Manager
# Copyright (C) 2015 Maxime Dor
#
# http://kamax.io/hbox/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

BASE_DIR=$(dirname $0)

cd "$BASE_DIR/.."
echo "Fetching API repo"
git clone https://github.com/hyperbox/api.git
echo

echo "Fetching Client repo"
git clone https://github.com/hyperbox/client.git
echo

echo "Fetching Server repo"
git clone https://github.com/hyperbox/server.git
echo

echo "Fetching VirtualBox common repo"
git clone https://github.com/hyperbox/vbox-common.git
echo

echo "Fetching VirtualBox 4.2 repo"
git clone https://github.com/hyperbox/vbox-4.2.git
echo

echo "Fetching VirtualBox 4.3 repo"
git clone https://github.com/hyperbox/vbox-4.3.git
echo

echo "Fetching VirtualBox 5.0 repo"
git clone https://github.com/hyperbox/vbox-5.0.git
echo

cd "$BASE_DIR"
