#!/bin/bash
###########################################################################
#
# Hyperbox - Enterprise Virtualization Manager
# Copyright (C) 2014 Maxime Dor
# 
# http://hyperbox.altherian.org
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or 
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

INSTALL_DIR="/opt/hboxd"
EXEC="java"
DAEMON_CLASS="org.altherian.hboxd.HyperboxHeadless"
CLASSPATH="$INSTALL_DIR/bin/*:$INSTALL_DIR/lib/*"
ARGS_START="-cp $CLASSPATH -Xmx75m -Xss2048k"

if [ $# -ge 1 ]; then
	INSTALL_DIR=$1
	shift 1
fi

cd $INSTALL_DIR
nohup java $ARGS_START "$@" $DAEMON_CLASS &> /dev/null &
echo $!
