#!/bin/bash
# Hyperbox - Enterprise Virtualization Manager
# Copyright (C) 2013 Maxime Dor
# maxime dot dor at altherian dot org
# 
# http://hyperbox.altherian.org
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation under version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

java -splash:icons/login-header.png -cp bin/*:lib/* org.altherian.hboxc.HyperboxClientApplicationStart "$@"
